### ISSUE TITLE
Server fills the entire disk with logs

### ISSUE THREAD

**Issue by tbrandysky** [LMS-Community/slimserver#1183]
I am running Raspberry Pi 4 Model B Rev 1.1

logitechmediaserver            8.5.2 deb package

In the last 6 years of running LMS, this happened to me for the second time:

thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', core/src/mercury/mod.rs:205:13
in syslog:

and then:
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x712514810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x1325ac810:  - <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x713514810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x1335ac810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x514810  - 714<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    0x1345ac810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x 514810715 - : <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x1355ac810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x 514810716 - :  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x5ac810  - 136<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7170x514810:  -  <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x 5ac810137 - : <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   7180x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 138<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7190x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810 139 - : <unknown>
Oct 15 07:00:40 LMS squeezeboxserver[421]:   7200x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810 -  140<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7210x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810 -  141<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7220x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 142<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7230x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 143<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:   0x724514810:   -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 144<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7250x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 145<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    0x726514810:  -   <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 146<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    7270x: 514810  -  <unknown>0x
Oct 15 07:00:40 LMS squeezeboxserver[421]: 5ac810  - 147<unknown>:
Oct 15 07:00:40 LMS squeezeboxserver[421]:    0x728514810:  -  <unknown> 0x

10GB of logs like this until the HDD was full on the server

**Comment by michaelherger** [comment]
LMS or the operating system should rotate the log files automatically. What log file is this? It doesn't look like one generated by LMS itself.

**Comment by tbrandysky** [comment]
This is daemon.log, managed by syslog (which also rotates logs automatically). It collects messages from LMS. 
The issue is some part in LMS crashed and LMS consequently generated 10GB of messages in just 2 days until it filled all free space with strange error messages.

It started with thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', core/src/mercury/mod.rs:205:13
and then 10GB of strange error messages like this for the rest of the free HDD space:

Another part of the messages (although it's still the same for the whole 10GB of logs):

Oct 16 21:01:58 LMS squeezeboxserver[421]: :    6156976 0x : 0x0x524810 51c8105ec810 -   - <unknown> - 0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: <unknown><unknown>5bc8106095475
Oct 16 21:01:58 LMS squeezeboxserver[421]:  - : 61115506186716<unknown> : :
Oct 16 21:01:58 LMS squeezeboxserver[421]:    61569770x  : 5248100x0x  - 51c8105ec810<unknown>  -  -
Oct 16 21:01:58 LMS squeezeboxserver[421]: <unknown><unknown>6095476
Oct 16 21:01:58 LMS squeezeboxserver[421]: : 61115516186717 : :    0x  0x5248100x5bc8100x - 5ec810 - 51c810<unknown> - <unknown> -
Oct 16 21:01:58 LMS squeezeboxserver[421]: <unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: <unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: 6095477
Oct 16 21:01:58 LMS squeezeboxserver[421]: 615697861867186111552: : : :         0x0x0x0x52481051c8105bc8105ec810 -  -  -  - <unknown><unknown><unknown><unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: 6095478611155361569796186719: : : :        0x 0x0x5248100x5bc8105ec810 -  - 51c810 - <unknown><unknown> - <unknown><unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: 6156980609547961867206111554: : : :  - 0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: : <unknown>59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:  -  <unknown> 61714066181876
Oct 16 21:01:58 LMS squeezeboxserver[421]: 0x: : 60c810  6177575 -   : <unknown>0x 0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: 574810 54c810 - 0x - <unknown>616792359c810<unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: :  -
Oct 16 21:01:58 LMS squeezeboxserver[421]:  6171407<unknown>6181877 : :
Oct 16 21:01:58 LMS squeezeboxserver[421]: 0x  60c8106177576   - : 0x0x<unknown> 54c810
Oct 16 21:01:58 LMS squeezeboxserver[421]: 574810  -  - 61679240x<unknown><unknown>: 59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:   - 6181878 6171408<unknown>: 0x:
Oct 16 21:01:58 LMS squeezeboxserver[421]: 60c810  6177577 -   : <unknown>0x0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: 57481054c810 6167925 -  - 0x: <unknown><unknown>59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:  -  61714096181879<unknown>0x: :
Oct 16 21:01:58 LMS squeezeboxserver[421]: 60c810  6177578 -   : <unknown>0x0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: 54c810574810 6167926 -  - 0x: <unknown><unknown>59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:  -  61818806171410<unknown>0x: :
Oct 16 21:01:58 LMS squeezeboxserver[421]: 60c810  6177579 -   : <unknown>0x0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: 54c810574810  - 6167927 - 0x<unknown>: <unknown>59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:  
Oct 16 21:01:58 LMS squeezeboxserver[421]:  - 6181881 6171411<unknown>: 0x:
Oct 16 21:01:58 LMS squeezeboxserver[421]:  60c810   - 6177580 0x<unknown>0x: 54c810
Oct 16 21:01:58 LMS squeezeboxserver[421]: 574810  - 6167928  - <unknown>: 0x<unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]:  59c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:   - 618188261714120x<unknown>: : 60c810
Oct 16 21:01:58 LMS squeezeboxserver[421]:    - 6177581 <unknown> : 0x
Oct 16 21:01:58 LMS squeezeboxserver[421]: 0x54c810 6167929574810 - :   - <unknown>0x <unknown>
Oct 16 21:01:58 LMS squeezeboxserver[421]: 59c810

**Comment by tbrandysky** [comment]
I also found this issue here:

https://forums.slimdevices.com/forum/user-forums/3rd-party-software/112342-spotty-4-7-0#post1514107

**Comment by tbrandysky** [comment]
I also use your Spotty plugin (which is great btw ;), don't know whether it's related somehow.

**Comment by michaelherger** [comment]
I'd need more of that log file to understand where those numbers are coming from. They might be a stack trace or something. But if the spotty was failing all the time, you'd noticed that spotty wouldn't work. Maybe you can send me a compressed copy of the most recent few hundred lines?

**Comment by tbrandysky** [comment]
here is the link to the compressed log containing only messages from LMS: 
https://drive.google.com/file/d/1kts09-tdrz61isfqtOqqkF35AjNAKJc6/view?usp=sharing

maybe line 567 could be some lead:

567  Oct 15 07:00:40 LMS squeezeboxserver[421]:  564:  thread ' 0xmain5ac810' panicked at ' - Spotify servers returned an error. Restart librespot.<unknown>',
   568  Oct 15 07:00:40 LMS squeezeboxserver[421]: core/src/mercury/mod.rs :565205: : 13
   569  Oct 15 07:00:40 LMS squeezeboxserver[421]: 0x5ac810stack backtrace:

I've been using Spotty for many years on a few devices at home almost every day. I haven't noticed any hiccups or crashes until this occasional incident.

**Comment by michaelherger** [comment]
That file is massive (135M lines). But it looks more like a Spotty issue than LMS. If you have Spotty Connect mode enabled, please disable it. Did that even work? It looks as if the connect helper was constantly crashing.

Did you build the Spotty helper yourself? Or is this a regular installation?

**Comment by tbrandysky** [comment]
I've used Spotty Connect only occasionally, but it worked just fine. I can disable it as I don't use it often. I didn't build anything myself, I use only regular installation from packages. 

As I mentioned before, this issue happened to me already once, maybe twice, in the last, let's say, 6-8 years using LMC on my RaspberryPi. It can be some coincidence because normally everything goes smoothly. But apparently, there is some hidden glitch somewhere.
